Updated Game with Error
This is the game with the tower code integrated with the penguin code. The projectile code is also here. 

Please note that the below error occurs when trying to run the code. The error comes from the arrays of slopeX, slopeY, slopXConstrain, and slopeYConstrain within the penguin class.

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at processing.core.PApplet.runSketch(PApplet.java:10741)
	at processing.core.PApplet.main(PApplet.java:10511)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at processing.core.PApplet.runSketch(PApplet.java:10735)
	... 1 more
Caused by: java.lang.NullPointerException
	at CPTD_TrackTest$Penguin.<init>(CPTD_TrackTest.java:116)
	at CPTD_TrackTest$Interface.<init>(CPTD_TrackTest.java:77)
	at CPTD_TrackTest.<init>(CPTD_TrackTest.java:19)
	... 6 more